language: python
python:
- '3.6'
- '3.7'
- '3.8'
before_install:
- python --version
- pip install -U pip
- pip install -r dev_requirements.txt
install:
- pip install -r requirements.txt
- python setup.py install
script:
- pytest --cov=llckbdm
- python setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  skip_cleanup: true
  skip_existing: true
  password:
    secure: l2ADmve9/HHZSoirdDO3GgpsCKfcNi0U3e+AkvLIsdOKlLYNgPNbumgpn/SKE6sfddwBx4PeG6nHj3cBxITKe4GO6L7vFcKdxrd1/iLWNou0mfijtNt2OAGpgQaFK3irRzaSLW8ecgHNBmafgTxAmTklqGaxjOpXB0jpwwHWl0yQV7qmJAu5DJjXutJxvi+P/dArQ6bYfMdeFHBkoiUwX64I1xXENOsax6O1GJ3uTI6d8g+8Dj4JI4z+qNNpmFW0DZmEba6E1uBIg77abCMfeCvXeJV1rAKVb15G0jGMEHauQmcSfO/YambnQJZtOg17F0QqKw8OLkm+9HlBc5mBosqNoMqOKqH1yfYgw9ZMkvEzarQ2b+YyRo09/bzvS4L6hE8X6LiGv5WHaM3EnjivisyVZIRA/2d7xptAxO0EJ7bSDhWIk5INUiHWqFWwO8JpGT0FooYKcdIHQAxrq6ERvvLWKlS7/cvIvbUkvt69J5tA392mbolp3GqU04rPsltKHOuAKTj15ezSW4bmzsSAIh8BBjVz/yv5EhtTJjKQKJMKxmrbiO7JyXd6C2qCNGmEGMYPZhkCZy0wgkzukMCYGQAegDu5c7Olz35SfpIK4EzO/BqpzG2opxtrwa4P5JO5lGI8WfPodVbFqfuXnj13xLQzTVV/EKZg/Jsdv+cYDFs=
  on:
    tags: true
    branch: master
