language: python
python:
- '3.6'
- '3.7'
- '3.8'
before_install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov pytest-cov
install:
- pip install -r requirements.txt
- python setup.py install
script:
- pytest --cov=llckbdm
- python setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  username: llckbdm_ci
  password:
    secure: dW/SjRjCt2fGUylbI6oybkRAoBXGRdeUJZ4U4Jic+qIazXtmEJpwaCprL2MYyAy9chLfU8VLQiQhDtTGuFas2UwYTtma0zYKNSvP4aRhEomyDb2yV5C5AoMAHprqVjhDucoiT7UWZyRE7SlpbXJGXJtewMQXiYch9aOYzgA0hWLVoTdv53y51h3RzzXNOGSQ/XNdMe5832UKlzP3NpSJXq1GdexRqAR5jybGTSu+undeowhDgpDJpUvneoBCneZqIecK+ShZ+ZBSs81RKmpLIHdWU5/TNstgaGUevFh2RYoZKk56RGuQIsBdSuMidgxfRCuynXww+kFckZYiU1hucIlHIEm4F6DePe3G78hE1dX0JEd6xjiN3Km0ho9GTCu7xb+YPh8N5tme90104/l5KTLu0ZLHCock6hBCi6CCN+CGLg7zOdenkMFUca6oSyl5RygxSUNwVKN4mYSZUPo08RbV1watL2bzlBb0R80v28qoZFGe36GqKoRx+DIuKFqR/anm1zp7Jt8+aOa96Lb+j9aD76N/QUqCXJvb8CNjIkDA8Cx2WmOdrkWi/pC/xWhN2X9lRrIDyP1ikTBUf/b9EneE0n4xE92DzWuha1ZuMleq0ojGhFQfF4TQcTN5dQPOYX9FuPhpanT+oFnWYVIle2baAAXoEyVLrkyqXwG8+ds=
  on:
    tags: true
    branch: master
