strategy:
  matrix:
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
  pythonVersion: '3.6'

steps:
  - checkout: self
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip codecov virtualenv pytest pytest-cov
      pip install -r requirements.txt
    displayName: 'Install prerequisites'

  - script: |
      py.test
    displayName: 'Testing'

  - script: |
      python setup.py install
    displayName: 'python setup.py install'

  - script: python setup.py test
    displayName: 'python setup.py test'
