pool:
  vmImage: 'VS2017-Win2016'

variables:
  pythonVersion: '3.6'

steps:
  - checkout: self
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip cython ninja cmake codecov scikit-build virtualenv pytest==4.0.2 pytest-cov==2.6.0
      pip install -r requirements.txt
    displayName: 'Install prerequisites'

  - script: mkdir build
    displayName: Make Build Directory

  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '-A x64 ..'
    displayName: CMake build

  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '--build . --target install'
    displayName: CMake install

  - script: |
      py.test
    displayName: 'Testing'

#  - script: |
#      python setup.py install
#      python setup.py test
#      cd ..
#      python -c "import llckbdm.bindings"
#      cd llckbdm
#    displayName: 'python setup.py install'
