pool:
  vmImage: 'VS2017-Win2016'

variables:
  pythonVersion: '3.6'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      architecture: 'x64'

- script: |
    python -m pip install --upgrade pip cython ninja cmake codecov scikit-build virtualenv
    pip install -r requirements.txt
  displayName: 'Install prerequisites'

- script: |
    python setup.py install
    python setup.py test
    cd ..
    python -c "import llckbdm.bindings"
    cd llckbdm
  displayName: 'python setup.py install'